"""empty message

Revision ID: 8f9768d865c0
Revises: e1cbd160f277
Create Date: 2021-06-15 23:39:23.778642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f9768d865c0'
down_revision = 'e1cbd160f277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leg', mysql.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
