"""empty message

Revision ID: b615d917ee6f
Revises: e4eeb970f20f
Create Date: 2021-06-17 18:30:22.558481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b615d917ee6f'
down_revision = 'e4eeb970f20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
