"""empty message

Revision ID: e1cbd160f277
Revises: 88538e8aca5a
Create Date: 2021-06-15 23:12:17.994047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cbd160f277'
down_revision = '88538e8aca5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leg', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leg')
    # ### end Alembic commands ###
