"""empty message

Revision ID: e4eeb970f20f
Revises: 8f9768d865c0
Create Date: 2021-06-17 22:16:47.824431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4eeb970f20f'
down_revision = '8f9768d865c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.Float(precision=10, asdecimal=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###
